//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Notification_DBEntities : DbContext
    {
        public Notification_DBEntities()
            : base("name=Notification_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cust> tbl_cust { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
